### ISSUE TITLE
Make a guard for "Galaxy APIs"

### ISSUE THREAD

**Issue by geooot** [tamu-datathon-org/gatekeeper#50]
- In like an Auth header it has the correct secret in order to let this request pass-through (to make sure that request is coming from another galaxy apps)
   - The secret should be in the env file
- This is on top of the AuthGuards as the galaxy app would also need to pass along the cookie (in most cases)

**Comment by phulsechinmay** [comment]
Are we thinking of having this check on the `login` and `signup` paths? Because if there are other endpoints we need this on, we'd need to propagate the header across requests. 

Can we maybe mimic the security offered by this by having a check for whether the redirect URLs are from a valid set of URLs?

**Comment by geooot** [comment]
@phulsechinmay no this is only for server to server communications, so only for the galaxy apis

**Comment by phulsechinmay** [comment]
@geooot So what kind of endpoints will this be on? The Auth check endpoints that APIs will hit?
